# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42aa767645ad5fc2fea8650845e8d7048ab593a9d673d4b6098c74ffa8606b742a8bcadfed7a7d9ce66dfe4f532806af70f30b584c6a81f12f0b2d0243318ab1

test:
  secret_key_base: fb6fcc64dcb234dea13357618d2670829572136d66b3d49e5f1ff8f301fdf3248aea37001b389bf733620286e52a5d64a4f6317944c87ff465ea35279c3470a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
